# Site settings
title: Dan Everton
email: dan@iocaine.org
description: Dan Everton's Scribblings
url: https://www.iocaine.org
twitter_username: dan_everton
github_username:  deverton

# Jekyll configuration
markdown: kramdown
gems:
    - jekyll-mentions
    - jemoji
    - jekyll-redirect-from
    - jekyll-sitemap

