# Site settings
title: Dan Everton
email: dan@iocaine.org
description: Dan Everton's Scribblings
baseurl: ""
url: "http://www.iocaine.org"
twitter_username: dan_everton
github_username:  deverton

# Build settings
markdown: kramdown
